//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmInitParameters) DeepCopyInto(out *ApmInitParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]TopologyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmInitParameters.
func (in *ApmInitParameters) DeepCopy() *ApmInitParameters {
	if in == nil {
		return nil
	}
	out := new(ApmInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmObservation) DeepCopyInto(out *ApmObservation) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]TopologyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmObservation.
func (in *ApmObservation) DeepCopy() *ApmObservation {
	if in == nil {
		return nil
	}
	out := new(ApmObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmParameters) DeepCopyInto(out *ApmParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]TopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmParameters.
func (in *ApmParameters) DeepCopy() *ApmParameters {
	if in == nil {
		return nil
	}
	out := new(ApmParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingInitParameters) DeepCopyInto(out *AutoscalingInitParameters) {
	*out = *in
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(string)
		**out = **in
	}
	if in.MaxSizeResource != nil {
		in, out := &in.MaxSizeResource, &out.MaxSizeResource
		*out = new(string)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(string)
		**out = **in
	}
	if in.MinSizeResource != nil {
		in, out := &in.MinSizeResource, &out.MinSizeResource
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingInitParameters.
func (in *AutoscalingInitParameters) DeepCopy() *AutoscalingInitParameters {
	if in == nil {
		return nil
	}
	out := new(AutoscalingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingObservation) DeepCopyInto(out *AutoscalingObservation) {
	*out = *in
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(string)
		**out = **in
	}
	if in.MaxSizeResource != nil {
		in, out := &in.MaxSizeResource, &out.MaxSizeResource
		*out = new(string)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(string)
		**out = **in
	}
	if in.MinSizeResource != nil {
		in, out := &in.MinSizeResource, &out.MinSizeResource
		*out = new(string)
		**out = **in
	}
	if in.PolicyOverrideJSON != nil {
		in, out := &in.PolicyOverrideJSON, &out.PolicyOverrideJSON
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingObservation.
func (in *AutoscalingObservation) DeepCopy() *AutoscalingObservation {
	if in == nil {
		return nil
	}
	out := new(AutoscalingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingParameters) DeepCopyInto(out *AutoscalingParameters) {
	*out = *in
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(string)
		**out = **in
	}
	if in.MaxSizeResource != nil {
		in, out := &in.MaxSizeResource, &out.MaxSizeResource
		*out = new(string)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(string)
		**out = **in
	}
	if in.MinSizeResource != nil {
		in, out := &in.MinSizeResource, &out.MinSizeResource
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingParameters.
func (in *AutoscalingParameters) DeepCopy() *AutoscalingParameters {
	if in == nil {
		return nil
	}
	out := new(AutoscalingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigInitParameters) DeepCopyInto(out *ConfigInitParameters) {
	*out = *in
	if in.DebugEnabled != nil {
		in, out := &in.DebugEnabled, &out.DebugEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigInitParameters.
func (in *ConfigInitParameters) DeepCopy() *ConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObservation) DeepCopyInto(out *ConfigObservation) {
	*out = *in
	if in.DebugEnabled != nil {
		in, out := &in.DebugEnabled, &out.DebugEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObservation.
func (in *ConfigObservation) DeepCopy() *ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigParameters) DeepCopyInto(out *ConfigParameters) {
	*out = *in
	if in.DebugEnabled != nil {
		in, out := &in.DebugEnabled, &out.DebugEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigParameters.
func (in *ConfigParameters) DeepCopy() *ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Deployment) DeepCopyInto(out *Deployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deployment.
func (in *Deployment) DeepCopy() *Deployment {
	if in == nil {
		return nil
	}
	out := new(Deployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Deployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentInitParameters) DeepCopyInto(out *DeploymentInitParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Apm != nil {
		in, out := &in.Apm, &out.Apm
		*out = make([]ApmInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentTemplateID != nil {
		in, out := &in.DeploymentTemplateID, &out.DeploymentTemplateID
		*out = new(string)
		**out = **in
	}
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = make([]ElasticsearchInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnterpriseSearch != nil {
		in, out := &in.EnterpriseSearch, &out.EnterpriseSearch
		*out = make([]EnterpriseSearchInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IntegrationsServer != nil {
		in, out := &in.IntegrationsServer, &out.IntegrationsServer
		*out = make([]IntegrationsServerInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Kibana != nil {
		in, out := &in.Kibana, &out.Kibana
		*out = make([]KibanaInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = make([]ObservabilityInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TrafficFilter != nil {
		in, out := &in.TrafficFilter, &out.TrafficFilter
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentInitParameters.
func (in *DeploymentInitParameters) DeepCopy() *DeploymentInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeploymentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentList) DeepCopyInto(out *DeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Deployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentList.
func (in *DeploymentList) DeepCopy() *DeploymentList {
	if in == nil {
		return nil
	}
	out := new(DeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentObservation) DeepCopyInto(out *DeploymentObservation) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Apm != nil {
		in, out := &in.Apm, &out.Apm
		*out = make([]ApmObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentTemplateID != nil {
		in, out := &in.DeploymentTemplateID, &out.DeploymentTemplateID
		*out = new(string)
		**out = **in
	}
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = make([]ElasticsearchObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchUsername != nil {
		in, out := &in.ElasticsearchUsername, &out.ElasticsearchUsername
		*out = new(string)
		**out = **in
	}
	if in.EnterpriseSearch != nil {
		in, out := &in.EnterpriseSearch, &out.EnterpriseSearch
		*out = make([]EnterpriseSearchObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IntegrationsServer != nil {
		in, out := &in.IntegrationsServer, &out.IntegrationsServer
		*out = make([]IntegrationsServerObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Kibana != nil {
		in, out := &in.Kibana, &out.Kibana
		*out = make([]KibanaObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = make([]ObservabilityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TrafficFilter != nil {
		in, out := &in.TrafficFilter, &out.TrafficFilter
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentObservation.
func (in *DeploymentObservation) DeepCopy() *DeploymentObservation {
	if in == nil {
		return nil
	}
	out := new(DeploymentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentParameters) DeepCopyInto(out *DeploymentParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Apm != nil {
		in, out := &in.Apm, &out.Apm
		*out = make([]ApmParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentTemplateID != nil {
		in, out := &in.DeploymentTemplateID, &out.DeploymentTemplateID
		*out = new(string)
		**out = **in
	}
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = make([]ElasticsearchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnterpriseSearch != nil {
		in, out := &in.EnterpriseSearch, &out.EnterpriseSearch
		*out = make([]EnterpriseSearchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IntegrationsServer != nil {
		in, out := &in.IntegrationsServer, &out.IntegrationsServer
		*out = make([]IntegrationsServerParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Kibana != nil {
		in, out := &in.Kibana, &out.Kibana
		*out = make([]KibanaParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = make([]ObservabilityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TrafficFilter != nil {
		in, out := &in.TrafficFilter, &out.TrafficFilter
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentParameters.
func (in *DeploymentParameters) DeepCopy() *DeploymentParameters {
	if in == nil {
		return nil
	}
	out := new(DeploymentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatus) DeepCopyInto(out *DeploymentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatus.
func (in *DeploymentStatus) DeepCopy() *DeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConfigInitParameters) DeepCopyInto(out *ElasticsearchConfigInitParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConfigInitParameters.
func (in *ElasticsearchConfigInitParameters) DeepCopy() *ElasticsearchConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConfigObservation) DeepCopyInto(out *ElasticsearchConfigObservation) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConfigObservation.
func (in *ElasticsearchConfigObservation) DeepCopy() *ElasticsearchConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConfigParameters) DeepCopyInto(out *ElasticsearchConfigParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConfigParameters.
func (in *ElasticsearchConfigParameters) DeepCopy() *ElasticsearchConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchInitParameters) DeepCopyInto(out *ElasticsearchInitParameters) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ElasticsearchConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = make([]ExtensionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.RemoteCluster != nil {
		in, out := &in.RemoteCluster, &out.RemoteCluster
		*out = make([]RemoteClusterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnapshotSource != nil {
		in, out := &in.SnapshotSource, &out.SnapshotSource
		*out = make([]SnapshotSourceInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = make([]StrategyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]ElasticsearchTopologyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustAccount != nil {
		in, out := &in.TrustAccount, &out.TrustAccount
		*out = make([]TrustAccountInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustExternal != nil {
		in, out := &in.TrustExternal, &out.TrustExternal
		*out = make([]TrustExternalInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchInitParameters.
func (in *ElasticsearchInitParameters) DeepCopy() *ElasticsearchInitParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchObservation) DeepCopyInto(out *ElasticsearchObservation) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(string)
		**out = **in
	}
	if in.CloudID != nil {
		in, out := &in.CloudID, &out.CloudID
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ElasticsearchConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = make([]ExtensionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RemoteCluster != nil {
		in, out := &in.RemoteCluster, &out.RemoteCluster
		*out = make([]RemoteClusterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.SnapshotSource != nil {
		in, out := &in.SnapshotSource, &out.SnapshotSource
		*out = make([]SnapshotSourceObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = make([]StrategyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]ElasticsearchTopologyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustAccount != nil {
		in, out := &in.TrustAccount, &out.TrustAccount
		*out = make([]TrustAccountObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustExternal != nil {
		in, out := &in.TrustExternal, &out.TrustExternal
		*out = make([]TrustExternalObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchObservation.
func (in *ElasticsearchObservation) DeepCopy() *ElasticsearchObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchParameters) DeepCopyInto(out *ElasticsearchParameters) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ElasticsearchConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = make([]ExtensionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.RemoteCluster != nil {
		in, out := &in.RemoteCluster, &out.RemoteCluster
		*out = make([]RemoteClusterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnapshotSource != nil {
		in, out := &in.SnapshotSource, &out.SnapshotSource
		*out = make([]SnapshotSourceParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = make([]StrategyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]ElasticsearchTopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustAccount != nil {
		in, out := &in.TrustAccount, &out.TrustAccount
		*out = make([]TrustAccountParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustExternal != nil {
		in, out := &in.TrustExternal, &out.TrustExternal
		*out = make([]TrustExternalParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchParameters.
func (in *ElasticsearchParameters) DeepCopy() *ElasticsearchParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchTopologyInitParameters) DeepCopyInto(out *ElasticsearchTopologyInitParameters) {
	*out = *in
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = make([]AutoscalingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeData != nil {
		in, out := &in.NodeTypeData, &out.NodeTypeData
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeIngest != nil {
		in, out := &in.NodeTypeIngest, &out.NodeTypeIngest
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeML != nil {
		in, out := &in.NodeTypeML, &out.NodeTypeML
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeMaster != nil {
		in, out := &in.NodeTypeMaster, &out.NodeTypeMaster
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchTopologyInitParameters.
func (in *ElasticsearchTopologyInitParameters) DeepCopy() *ElasticsearchTopologyInitParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchTopologyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchTopologyObservation) DeepCopyInto(out *ElasticsearchTopologyObservation) {
	*out = *in
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = make([]AutoscalingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]TopologyConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.NodeRoles != nil {
		in, out := &in.NodeRoles, &out.NodeRoles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NodeTypeData != nil {
		in, out := &in.NodeTypeData, &out.NodeTypeData
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeIngest != nil {
		in, out := &in.NodeTypeIngest, &out.NodeTypeIngest
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeML != nil {
		in, out := &in.NodeTypeML, &out.NodeTypeML
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeMaster != nil {
		in, out := &in.NodeTypeMaster, &out.NodeTypeMaster
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchTopologyObservation.
func (in *ElasticsearchTopologyObservation) DeepCopy() *ElasticsearchTopologyObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchTopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchTopologyParameters) DeepCopyInto(out *ElasticsearchTopologyParameters) {
	*out = *in
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = make([]AutoscalingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeData != nil {
		in, out := &in.NodeTypeData, &out.NodeTypeData
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeIngest != nil {
		in, out := &in.NodeTypeIngest, &out.NodeTypeIngest
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeML != nil {
		in, out := &in.NodeTypeML, &out.NodeTypeML
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeMaster != nil {
		in, out := &in.NodeTypeMaster, &out.NodeTypeMaster
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchTopologyParameters.
func (in *ElasticsearchTopologyParameters) DeepCopy() *ElasticsearchTopologyParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchTopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchConfigInitParameters) DeepCopyInto(out *EnterpriseSearchConfigInitParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchConfigInitParameters.
func (in *EnterpriseSearchConfigInitParameters) DeepCopy() *EnterpriseSearchConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchConfigObservation) DeepCopyInto(out *EnterpriseSearchConfigObservation) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchConfigObservation.
func (in *EnterpriseSearchConfigObservation) DeepCopy() *EnterpriseSearchConfigObservation {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchConfigParameters) DeepCopyInto(out *EnterpriseSearchConfigParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchConfigParameters.
func (in *EnterpriseSearchConfigParameters) DeepCopy() *EnterpriseSearchConfigParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchInitParameters) DeepCopyInto(out *EnterpriseSearchInitParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]EnterpriseSearchConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]EnterpriseSearchTopologyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchInitParameters.
func (in *EnterpriseSearchInitParameters) DeepCopy() *EnterpriseSearchInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchObservation) DeepCopyInto(out *EnterpriseSearchObservation) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]EnterpriseSearchConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]EnterpriseSearchTopologyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchObservation.
func (in *EnterpriseSearchObservation) DeepCopy() *EnterpriseSearchObservation {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchParameters) DeepCopyInto(out *EnterpriseSearchParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]EnterpriseSearchConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]EnterpriseSearchTopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchParameters.
func (in *EnterpriseSearchParameters) DeepCopy() *EnterpriseSearchParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchTopologyInitParameters) DeepCopyInto(out *EnterpriseSearchTopologyInitParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchTopologyInitParameters.
func (in *EnterpriseSearchTopologyInitParameters) DeepCopy() *EnterpriseSearchTopologyInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchTopologyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchTopologyObservation) DeepCopyInto(out *EnterpriseSearchTopologyObservation) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeAppserver != nil {
		in, out := &in.NodeTypeAppserver, &out.NodeTypeAppserver
		*out = new(bool)
		**out = **in
	}
	if in.NodeTypeConnector != nil {
		in, out := &in.NodeTypeConnector, &out.NodeTypeConnector
		*out = new(bool)
		**out = **in
	}
	if in.NodeTypeWorker != nil {
		in, out := &in.NodeTypeWorker, &out.NodeTypeWorker
		*out = new(bool)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchTopologyObservation.
func (in *EnterpriseSearchTopologyObservation) DeepCopy() *EnterpriseSearchTopologyObservation {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchTopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchTopologyParameters) DeepCopyInto(out *EnterpriseSearchTopologyParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchTopologyParameters.
func (in *EnterpriseSearchTopologyParameters) DeepCopy() *EnterpriseSearchTopologyParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchTopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionInitParameters) DeepCopyInto(out *ExtensionInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionInitParameters.
func (in *ExtensionInitParameters) DeepCopy() *ExtensionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ExtensionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionObservation) DeepCopyInto(out *ExtensionObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionObservation.
func (in *ExtensionObservation) DeepCopy() *ExtensionObservation {
	if in == nil {
		return nil
	}
	out := new(ExtensionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionParameters) DeepCopyInto(out *ExtensionParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionParameters.
func (in *ExtensionParameters) DeepCopy() *ExtensionParameters {
	if in == nil {
		return nil
	}
	out := new(ExtensionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerConfigInitParameters) DeepCopyInto(out *IntegrationsServerConfigInitParameters) {
	*out = *in
	if in.DebugEnabled != nil {
		in, out := &in.DebugEnabled, &out.DebugEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerConfigInitParameters.
func (in *IntegrationsServerConfigInitParameters) DeepCopy() *IntegrationsServerConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerConfigObservation) DeepCopyInto(out *IntegrationsServerConfigObservation) {
	*out = *in
	if in.DebugEnabled != nil {
		in, out := &in.DebugEnabled, &out.DebugEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerConfigObservation.
func (in *IntegrationsServerConfigObservation) DeepCopy() *IntegrationsServerConfigObservation {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerConfigParameters) DeepCopyInto(out *IntegrationsServerConfigParameters) {
	*out = *in
	if in.DebugEnabled != nil {
		in, out := &in.DebugEnabled, &out.DebugEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerConfigParameters.
func (in *IntegrationsServerConfigParameters) DeepCopy() *IntegrationsServerConfigParameters {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerInitParameters) DeepCopyInto(out *IntegrationsServerInitParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]IntegrationsServerConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]IntegrationsServerTopologyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerInitParameters.
func (in *IntegrationsServerInitParameters) DeepCopy() *IntegrationsServerInitParameters {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerObservation) DeepCopyInto(out *IntegrationsServerObservation) {
	*out = *in
	if in.ApmHTTPSEndpoint != nil {
		in, out := &in.ApmHTTPSEndpoint, &out.ApmHTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]IntegrationsServerConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.FleetHTTPSEndpoint != nil {
		in, out := &in.FleetHTTPSEndpoint, &out.FleetHTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]IntegrationsServerTopologyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerObservation.
func (in *IntegrationsServerObservation) DeepCopy() *IntegrationsServerObservation {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerParameters) DeepCopyInto(out *IntegrationsServerParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]IntegrationsServerConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]IntegrationsServerTopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerParameters.
func (in *IntegrationsServerParameters) DeepCopy() *IntegrationsServerParameters {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerTopologyInitParameters) DeepCopyInto(out *IntegrationsServerTopologyInitParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerTopologyInitParameters.
func (in *IntegrationsServerTopologyInitParameters) DeepCopy() *IntegrationsServerTopologyInitParameters {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerTopologyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerTopologyObservation) DeepCopyInto(out *IntegrationsServerTopologyObservation) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerTopologyObservation.
func (in *IntegrationsServerTopologyObservation) DeepCopy() *IntegrationsServerTopologyObservation {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerTopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsServerTopologyParameters) DeepCopyInto(out *IntegrationsServerTopologyParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsServerTopologyParameters.
func (in *IntegrationsServerTopologyParameters) DeepCopy() *IntegrationsServerTopologyParameters {
	if in == nil {
		return nil
	}
	out := new(IntegrationsServerTopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaConfigInitParameters) DeepCopyInto(out *KibanaConfigInitParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaConfigInitParameters.
func (in *KibanaConfigInitParameters) DeepCopy() *KibanaConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaConfigObservation) DeepCopyInto(out *KibanaConfigObservation) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaConfigObservation.
func (in *KibanaConfigObservation) DeepCopy() *KibanaConfigObservation {
	if in == nil {
		return nil
	}
	out := new(KibanaConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaConfigParameters) DeepCopyInto(out *KibanaConfigParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaConfigParameters.
func (in *KibanaConfigParameters) DeepCopy() *KibanaConfigParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaInitParameters) DeepCopyInto(out *KibanaInitParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]KibanaConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]KibanaTopologyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaInitParameters.
func (in *KibanaInitParameters) DeepCopy() *KibanaInitParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaObservation) DeepCopyInto(out *KibanaObservation) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]KibanaConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]KibanaTopologyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaObservation.
func (in *KibanaObservation) DeepCopy() *KibanaObservation {
	if in == nil {
		return nil
	}
	out := new(KibanaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaParameters) DeepCopyInto(out *KibanaParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]KibanaConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]KibanaTopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaParameters.
func (in *KibanaParameters) DeepCopy() *KibanaParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaTopologyInitParameters) DeepCopyInto(out *KibanaTopologyInitParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaTopologyInitParameters.
func (in *KibanaTopologyInitParameters) DeepCopy() *KibanaTopologyInitParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaTopologyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaTopologyObservation) DeepCopyInto(out *KibanaTopologyObservation) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaTopologyObservation.
func (in *KibanaTopologyObservation) DeepCopy() *KibanaTopologyObservation {
	if in == nil {
		return nil
	}
	out := new(KibanaTopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaTopologyParameters) DeepCopyInto(out *KibanaTopologyParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaTopologyParameters.
func (in *KibanaTopologyParameters) DeepCopy() *KibanaTopologyParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaTopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityInitParameters) DeepCopyInto(out *ObservabilityInitParameters) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(bool)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(bool)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityInitParameters.
func (in *ObservabilityInitParameters) DeepCopy() *ObservabilityInitParameters {
	if in == nil {
		return nil
	}
	out := new(ObservabilityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityObservation) DeepCopyInto(out *ObservabilityObservation) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(bool)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(bool)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityObservation.
func (in *ObservabilityObservation) DeepCopy() *ObservabilityObservation {
	if in == nil {
		return nil
	}
	out := new(ObservabilityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityParameters) DeepCopyInto(out *ObservabilityParameters) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(bool)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(bool)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityParameters.
func (in *ObservabilityParameters) DeepCopy() *ObservabilityParameters {
	if in == nil {
		return nil
	}
	out := new(ObservabilityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterInitParameters) DeepCopyInto(out *RemoteClusterInitParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.SkipUnavailable != nil {
		in, out := &in.SkipUnavailable, &out.SkipUnavailable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterInitParameters.
func (in *RemoteClusterInitParameters) DeepCopy() *RemoteClusterInitParameters {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterObservation) DeepCopyInto(out *RemoteClusterObservation) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.SkipUnavailable != nil {
		in, out := &in.SkipUnavailable, &out.SkipUnavailable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterObservation.
func (in *RemoteClusterObservation) DeepCopy() *RemoteClusterObservation {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterParameters) DeepCopyInto(out *RemoteClusterParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.SkipUnavailable != nil {
		in, out := &in.SkipUnavailable, &out.SkipUnavailable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterParameters.
func (in *RemoteClusterParameters) DeepCopy() *RemoteClusterParameters {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSourceInitParameters) DeepCopyInto(out *SnapshotSourceInitParameters) {
	*out = *in
	if in.SnapshotName != nil {
		in, out := &in.SnapshotName, &out.SnapshotName
		*out = new(string)
		**out = **in
	}
	if in.SourceElasticsearchClusterID != nil {
		in, out := &in.SourceElasticsearchClusterID, &out.SourceElasticsearchClusterID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSourceInitParameters.
func (in *SnapshotSourceInitParameters) DeepCopy() *SnapshotSourceInitParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotSourceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSourceObservation) DeepCopyInto(out *SnapshotSourceObservation) {
	*out = *in
	if in.SnapshotName != nil {
		in, out := &in.SnapshotName, &out.SnapshotName
		*out = new(string)
		**out = **in
	}
	if in.SourceElasticsearchClusterID != nil {
		in, out := &in.SourceElasticsearchClusterID, &out.SourceElasticsearchClusterID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSourceObservation.
func (in *SnapshotSourceObservation) DeepCopy() *SnapshotSourceObservation {
	if in == nil {
		return nil
	}
	out := new(SnapshotSourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSourceParameters) DeepCopyInto(out *SnapshotSourceParameters) {
	*out = *in
	if in.SnapshotName != nil {
		in, out := &in.SnapshotName, &out.SnapshotName
		*out = new(string)
		**out = **in
	}
	if in.SourceElasticsearchClusterID != nil {
		in, out := &in.SourceElasticsearchClusterID, &out.SourceElasticsearchClusterID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSourceParameters.
func (in *SnapshotSourceParameters) DeepCopy() *SnapshotSourceParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotSourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyInitParameters) DeepCopyInto(out *StrategyInitParameters) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyInitParameters.
func (in *StrategyInitParameters) DeepCopy() *StrategyInitParameters {
	if in == nil {
		return nil
	}
	out := new(StrategyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyObservation) DeepCopyInto(out *StrategyObservation) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyObservation.
func (in *StrategyObservation) DeepCopy() *StrategyObservation {
	if in == nil {
		return nil
	}
	out := new(StrategyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyParameters) DeepCopyInto(out *StrategyParameters) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyParameters.
func (in *StrategyParameters) DeepCopy() *StrategyParameters {
	if in == nil {
		return nil
	}
	out := new(StrategyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyConfigInitParameters) DeepCopyInto(out *TopologyConfigInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyConfigInitParameters.
func (in *TopologyConfigInitParameters) DeepCopy() *TopologyConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(TopologyConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyConfigObservation) DeepCopyInto(out *TopologyConfigObservation) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyConfigObservation.
func (in *TopologyConfigObservation) DeepCopy() *TopologyConfigObservation {
	if in == nil {
		return nil
	}
	out := new(TopologyConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyConfigParameters) DeepCopyInto(out *TopologyConfigParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyConfigParameters.
func (in *TopologyConfigParameters) DeepCopy() *TopologyConfigParameters {
	if in == nil {
		return nil
	}
	out := new(TopologyConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInitParameters) DeepCopyInto(out *TopologyInitParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInitParameters.
func (in *TopologyInitParameters) DeepCopy() *TopologyInitParameters {
	if in == nil {
		return nil
	}
	out := new(TopologyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyObservation) DeepCopyInto(out *TopologyObservation) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyObservation.
func (in *TopologyObservation) DeepCopy() *TopologyObservation {
	if in == nil {
		return nil
	}
	out := new(TopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyParameters) DeepCopyInto(out *TopologyParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyParameters.
func (in *TopologyParameters) DeepCopy() *TopologyParameters {
	if in == nil {
		return nil
	}
	out := new(TopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustAccountInitParameters) DeepCopyInto(out *TrustAccountInitParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.TrustAll != nil {
		in, out := &in.TrustAll, &out.TrustAll
		*out = new(bool)
		**out = **in
	}
	if in.TrustAllowlist != nil {
		in, out := &in.TrustAllowlist, &out.TrustAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustAccountInitParameters.
func (in *TrustAccountInitParameters) DeepCopy() *TrustAccountInitParameters {
	if in == nil {
		return nil
	}
	out := new(TrustAccountInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustAccountObservation) DeepCopyInto(out *TrustAccountObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.TrustAll != nil {
		in, out := &in.TrustAll, &out.TrustAll
		*out = new(bool)
		**out = **in
	}
	if in.TrustAllowlist != nil {
		in, out := &in.TrustAllowlist, &out.TrustAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustAccountObservation.
func (in *TrustAccountObservation) DeepCopy() *TrustAccountObservation {
	if in == nil {
		return nil
	}
	out := new(TrustAccountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustAccountParameters) DeepCopyInto(out *TrustAccountParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.TrustAll != nil {
		in, out := &in.TrustAll, &out.TrustAll
		*out = new(bool)
		**out = **in
	}
	if in.TrustAllowlist != nil {
		in, out := &in.TrustAllowlist, &out.TrustAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustAccountParameters.
func (in *TrustAccountParameters) DeepCopy() *TrustAccountParameters {
	if in == nil {
		return nil
	}
	out := new(TrustAccountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustExternalInitParameters) DeepCopyInto(out *TrustExternalInitParameters) {
	*out = *in
	if in.RelationshipID != nil {
		in, out := &in.RelationshipID, &out.RelationshipID
		*out = new(string)
		**out = **in
	}
	if in.TrustAll != nil {
		in, out := &in.TrustAll, &out.TrustAll
		*out = new(bool)
		**out = **in
	}
	if in.TrustAllowlist != nil {
		in, out := &in.TrustAllowlist, &out.TrustAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustExternalInitParameters.
func (in *TrustExternalInitParameters) DeepCopy() *TrustExternalInitParameters {
	if in == nil {
		return nil
	}
	out := new(TrustExternalInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustExternalObservation) DeepCopyInto(out *TrustExternalObservation) {
	*out = *in
	if in.RelationshipID != nil {
		in, out := &in.RelationshipID, &out.RelationshipID
		*out = new(string)
		**out = **in
	}
	if in.TrustAll != nil {
		in, out := &in.TrustAll, &out.TrustAll
		*out = new(bool)
		**out = **in
	}
	if in.TrustAllowlist != nil {
		in, out := &in.TrustAllowlist, &out.TrustAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustExternalObservation.
func (in *TrustExternalObservation) DeepCopy() *TrustExternalObservation {
	if in == nil {
		return nil
	}
	out := new(TrustExternalObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustExternalParameters) DeepCopyInto(out *TrustExternalParameters) {
	*out = *in
	if in.RelationshipID != nil {
		in, out := &in.RelationshipID, &out.RelationshipID
		*out = new(string)
		**out = **in
	}
	if in.TrustAll != nil {
		in, out := &in.TrustAll, &out.TrustAll
		*out = new(bool)
		**out = **in
	}
	if in.TrustAllowlist != nil {
		in, out := &in.TrustAllowlist, &out.TrustAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustExternalParameters.
func (in *TrustExternalParameters) DeepCopy() *TrustExternalParameters {
	if in == nil {
		return nil
	}
	out := new(TrustExternalParameters)
	in.DeepCopyInto(out)
	return out
}
